# Generated by Django 2.2 on 2020-11-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('useradd', models.CharField(max_length=20)),
                ('activity_name', models.CharField(max_length=20)),
                ('start_datetime', models.DateTimeField(max_length=50)),
                ('end_datetime', models.DateTimeField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('all_day', models.CharField(default='false', max_length=5)),
                ('color', models.CharField(default='#ba6ff5', max_length=7)),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'booking_activitynew',
            },
        ),
        migrations.CreateModel(
            name='BookingNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('useradd', models.CharField(max_length=20)),
                ('spaces_name', models.CharField(max_length=20)),
                ('start_datetime', models.DateTimeField(max_length=50)),
                ('end_datetime', models.DateTimeField(max_length=20)),
                ('fee', models.FloatField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('all_day', models.CharField(default='false', max_length=5)),
                ('color', models.CharField(default='#ba6ff5', max_length=7)),
            ],
            options={
                'verbose_name': '租用空间',
                'verbose_name_plural': '租用空间',
                'db_table': 'booking_bookingnew',
            },
        ),
        migrations.CreateModel(
            name='SpacesAdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spaces_name', models.CharField(max_length=20)),
                ('fee', models.FloatField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '空间增加',
                'verbose_name_plural': '空间增加',
                'db_table': 'booking_spacesadd',
            },
        ),
    ]
